[build]
  command = "pnpm build"
  publish = "dist/spa"
  environment = { SECRETS_SCAN_ENABLED = "false" }

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

[build.environment]
  SECRETS_SCAN_ENABLED = "false"
  SECRETS_SCAN_OMIT_PATHS = "dist/**,build/**,node_modules/**,.git/**"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
