[build]
  # Build command for the frontend
  command = "npm run build:netlify"
  
  # Directory where the built files will be located
  publish = "dist/spa"
  
  # Functions directory
  functions = "netlify/functions"

  

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # NPM version
  NPM_VERSION = "9"
  
  # Disable secret scanning
  SECRETS_SCAN_ENABLED = "false"
  
  # Unset Google Application Credentials to use explicit credentials instead
  GOOGLE_APPLICATION_CREDENTIALS = ""
  
  # Omit these keys from secret scanning (they are legitimate environment variables)
  SECRETS_SCAN_OMIT_KEYS = "GOOGLE_CLOUD_LOCATION,GOOGLE_CLOUD_UNIVERSE_DOMAIN,NODE_ENV,PORT,GOOGLE_CLOUD_TOKEN_URI,GOOGLE_CLOUD_AUTH_URI,GOOGLE_CLOUD_AUTH_PROVIDER_X509_CERT_URL,FIREBASE_PROJECT_ID,VITE_FIREBASE_MESSAGING_SENDER_ID,FIREBASE_APP_ID,FIREBASE_API_KEY,FIREBASE_AUTH_DOMAIN,FIREBASE_STORAGE_BUCKET,GOOGLE_CLOUD_PROJECT_ID,GOOGLE_CLOUD_PRIVATE_KEY_ID,GOOGLE_CLOUD_PRIVATE_KEY,GOOGLE_CLOUD_CLIENT_EMAIL,GOOGLE_CLOUD_CLIENT_ID,GOOGLE_CLOUD_CLIENT_X509_CERT_URL,GOOGLE_MAPS_API_KEY,GOOGLE_CLOUD_API_KEY,FIREBASE_SERVICE_ACCOUNT_KEY,FIREBASE_ADMIN_PROJECT_ID,FIREBASE_ADMIN_CLIENT_EMAIL,FIREBASE_ADMIN_PRIVATE_KEY"
  
  # Omit these paths from secret scanning
  SECRETS_SCAN_OMIT_PATHS = "dist/,server/routes/,env.production.template"

# Disable secret scanning
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Disable security scanning
[build.security]
  # Disable secret scanning
  secret_scanning = false

# Redirect rules for SPA routing
[[redirects]]
  # Handle API routes - must come before catch-all
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  # Handle client-side routing for React Router - catch-all must be last
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache service worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Environment variables (these will be set in Netlify dashboard)
# [build.environment]
#   VITE_FIREBASE_API_KEY = "your-firebase-api-key"
#   VITE_FIREBASE_AUTH_DOMAIN = "your-project.firebaseapp.com"
#   VITE_FIREBASE_PROJECT_ID = "your-project-id"
#   VITE_FIREBASE_STORAGE_BUCKET = "your-project.appspot.com"
#   VITE_FIREBASE_MESSAGING_SENDER_ID = "123456789"
#   VITE_FIREBASE_APP_ID = "1:123456789:web:abcdef123456"
#   FIREBASE_PROJECT_ID = "your-firebase-project-id"
#   FIREBASE_PRIVATE_KEY = "your-firebase-private-key"
#   FIREBASE_CLIENT_EMAIL = "your-service-account@your-project.iam.gserviceaccount.com"
#   GOOGLE_CLOUD_API_KEY = "your-gemini-api-key"
