[build]
  # Build command for the frontend
  command = "npm run build:netlify"
  
  # Directory where the built files will be located
  publish = "dist/spa"
  
  # Functions directory
  functions = "netlify/functions"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # NPM version
  NPM_VERSION = "9"

# Redirect rules for SPA routing
[[redirects]]
  # Handle API routes
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

# Handle client-side routing for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache service worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Function configuration
[functions]
  # Timeout for functions (in seconds)
  timeout = 30
  
  # Memory allocation
  memory = 1024

# Environment variables (these will be set in Netlify dashboard)
# [build.environment]
#   VITE_FIREBASE_API_KEY = "your-firebase-api-key"
#   VITE_FIREBASE_AUTH_DOMAIN = "your-project.firebaseapp.com"
#   VITE_FIREBASE_PROJECT_ID = "your-project-id"
#   VITE_FIREBASE_STORAGE_BUCKET = "your-project.appspot.com"
#   VITE_FIREBASE_MESSAGING_SENDER_ID = "123456789"
#   VITE_FIREBASE_APP_ID = "1:123456789:web:abcdef123456"
#   FIREBASE_PROJECT_ID = "your-firebase-project-id"
#   FIREBASE_PRIVATE_KEY = "your-firebase-private-key"
#   FIREBASE_CLIENT_EMAIL = "your-service-account@your-project.iam.gserviceaccount.com"
#   GOOGLE_CLOUD_API_KEY = "your-gemini-api-key"
